version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mbti_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mbti_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mbti_backend
    restart: always
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db
    networks:
      - mbti_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_URL=https://api.marinka-ai.ru
    container_name: mbti_frontend
    restart: always
    environment:
      VITE_API_URL: "https://api.marinka-ai.ru"
    networks:
      - mbti_network

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - mbti_network

networks:
  mbti_network:
    driver: bridge

volumes:
  postgres_data:
  npm_data:
  npm_letsencrypt:
