version: '3.8'

services:
  # 1. Наша база данных
  db:
    image: postgres:15
    container_name: mbti_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mbti_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Наш бэкенд (Python + FastAPI)
  backend:
    build: .
    container_name: mbti_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # 3. Наш фронтенд (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mbti_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  postgres_data:
